languages = { "af"   : "Afrikaans",
              "sq"   : "Albanian",
              "ar"   : "Arabic",
              "hy"   : "Armenian",
              "bs"   : "Bosnian",
              "ca"   : "Catalan",
              "zh-CN": "Chinese Simplified",
              "zh-TW": "Chinese Traditional",
              "hr"   : "Croatian",
              "cs"   : "Czech",
              "da"   : "Danish",
              "nl"   : "Dutch",
              "en"   : "English",
              "eo"   : "Esperanto",
              "fi"   : "Finnish",
              "fr"   : "French",
              "de"   : "German",
              "el"   : "Greek",
              "ht"   : "Haitian Creole",
              "hi"   : "Hindi",
              "hu"   : "Hungarian",
              "is"   : "Icelandic",
              "id"   : "Indonesian",
              "it"   : "Italian",
              "ja"   : "Japanese",
              "ko"   : "Korean",
              "la"   : "Latin",
              "lv"   : "Latvian",
              "mk"   : "Macedonian",
              "no"   : "Norwegian",
              "pl"   : "Polish",
              "pt"   : "Portuguese",
              "ro"   : "Romanian",
              "ru"   : "Russian",
              "sr"   : "Serbian",
              "sk"   : "Slovak",
              "es"   : "Spanish",
              "sw"   : "Swahili",
              "sv"   : "Swedish",
              "ta"   : "Tamil",
              "th"   : "Thai",
              "tr"   : "Turkish",
              "vi"   : "Vietnamese",
              "cy"   : "Welsh"
            }

def sort_by_value():
    return [(k, languages[k]) for k in sorted(languages, key=languages.get)]
